#!/bin/bash

addLocalBinDirToPath() {
  LOCAL_BIN_DIR=$DOTFILES_LOCAL/bin
  if [ -d $LOCAL_BIN_DIR ]; then
    echo -e "\nAdd local bin dir $LOCAL_BIN_DIR in \$PATH"
    export PATH=$LOCAL_BIN_DIR:$PATH
  fi
}

if [ -d "$DOTFILES_LOCAL" ];
  then
    echo -e "---------- Local config LOAD ----------"
    
    for f ($DOTFILES_LOCAL/zsh/*)
    do
      if [ -f "$f" ]; then
        echo -e "\nSource zsh local file $f found"
        source $f
      fi
    done

    addLocalBinDirToPath

    echo -e "---------- Local config LOADED ----------"
  else
    echo -e "---------- No local config found in $DOTFILES_LOCAL ----------"
fi



