#!/bin/bash

# TODO: rework to make simple for ... withot expand via find
ZSH_LOCAL_FILES=`find ${DOTFILES_LOCAL}/zsh/* -maxdepth 1 -type f`

echo -e "---------- Load local config ----------\n"

for f in $ZSH_LOCAL_FILES
do
  if [ -f "$f" ]; then
    echo "source zsh local file $f found"
    source $f
  fi
done


LOCAL_BIN_DIR=$DOTFILES_LOCAL/bin
if [ -d $LOCAL_BIN_DIR ]; then
  echo -e "\nAdd local bin dir $LOCAL_BIN_DIR in \$PATH"
  export PATH=$LOCAL_BIN_DIR:$PATH
fi

echo -e "----------- \n"
